/*
 * OasSample
 *
 * OpenAPI Sample with Go
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"log"
	"net/http"

	app "oasSample/app"
	openapi "oasSample/openapi"

	"github.com/gobuffalo/packr"
	"github.com/zserge/lorca"
)

func main() {
	go func() {
		//log.Printf("Server started")
		apiBox := packr.NewBox("./api")
		swaggerBox := packr.NewBox("./html/ui")
		SampledataApiService := app.NewSampledataApiService()
		SampledataApiController := openapi.NewSampledataApiController(SampledataApiService)

		router := openapi.NewRouter(SampledataApiController)

		router.PathPrefix("/ui/").Handler(http.StripPrefix("/ui/", http.FileServer(swaggerBox)))
		router.PathPrefix("/api/").Handler(http.StripPrefix("/api/", http.FileServer(apiBox)))

		log.Fatal(http.ListenAndServe(":3000", router))
	}()
	var ui lorca.UI
	ui, _ = lorca.New("", "", 1280, 768)
	defer ui.Close()

	ui.Load("http://localhost:3000/ui/")
	<-ui.Done()
}
