/*
 * OasSample
 *
 * OpenAPI Sample with Go
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"log"
	"net/http"

	app "oasSample/app"
	openapi "oasSample/openapi"
)

func main() {
	log.Printf("Server started")

	SampledataApiService := app.NewSampledataApiService()
	SampledataApiController := openapi.NewSampledataApiController(SampledataApiService)

	router := openapi.NewRouter(SampledataApiController)

	router.PathPrefix("/ui/").Handler(http.StripPrefix("/ui/", http.FileServer(http.Dir("html/ui"))))
	router.PathPrefix("/api/").Handler(http.StripPrefix("/api/", http.FileServer(http.Dir("api"))))

	log.Fatal(http.ListenAndServe(":3000", router))
}
