/*
 * OasSample
 *
 * OpenAPI Sample with Go
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"net/http"
)


// SampledataApiRouter defines the required methods for binding the api requests to a responses for the SampledataApi
// The SampledataApiRouter implementation should parse necessary information from the http request, 
// pass the data to a SampledataApiServicer to perform the required actions, then write the service results to the http response.
type SampledataApiRouter interface { 
	GetSampleDataDataId(http.ResponseWriter, *http.Request)
	PutSampleDataDataId(http.ResponseWriter, *http.Request)
}


// SampledataApiServicer defines the api actions for the SampledataApi service
// This interface intended to stay up to date with the openapi yaml used to generate it, 
// while the service implementation can ignored with the .openapi-generator-ignore file 
// and updated with the logic required for the API.
type SampledataApiServicer interface { 
	GetSampleDataDataId(string) (interface{}, error)
	PutSampleDataDataId(string, SampleData) (interface{}, error)
}
