/*
 * OasSample
 *
 * OpenAPI Sample with Go
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"errors"
)

// SampledataApiService is a service that implents the logic for the SampledataApiServicer
// This service should implement the business logic for every endpoint for the SampledataApi API. 
// Include any external packages or services that will be required by this service.
type SampledataApiService struct {
}

// NewSampledataApiService creates a default api service
func NewSampledataApiService() SampledataApiServicer {
	return &SampledataApiService{}
}

// GetSampleDataDataId - Get SampleData
func (s *SampledataApiService) GetSampleDataDataId(dataId string) (interface{}, error) {
	// TODO - update GetSampleDataDataId with the required logic for this service method.
	// Add api_sampledata_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.
	return nil, errors.New("service method 'GetSampleDataDataId' not implemented")
}

// PutSampleDataDataId - Update SampleData
func (s *SampledataApiService) PutSampleDataDataId(dataId string, sampleData SampleData) (interface{}, error) {
	// TODO - update PutSampleDataDataId with the required logic for this service method.
	// Add api_sampledata_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.
	return nil, errors.New("service method 'PutSampleDataDataId' not implemented")
}
