/*
 * OasSample
 *
 * OpenAPI Sample with Go
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type SampleResponse struct {

	Errorid string `json:"errorid,omitempty"`

	Level string `json:"level,omitempty"`

	Message string `json:"message,omitempty"`
}
