/*
 * OasSample
 *
 * OpenAPI Sample with Go
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// SampleData - Sample Data Model
type SampleData struct {

	DataId string `json:"data_id,omitempty"`

	Value1 float32 `json:"value1,omitempty"`

	Value2 int32 `json:"value2,omitempty"`

	Items string `json:"items,omitempty"`
}
